version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./auth/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./auth/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    container_name: db-mysql
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend
networks:
  frontend:
  backend: